// Date: 19/08/2012 17:52:55
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelATM extends ModelBase
{
  //fields
    ModelRenderer ATMBase;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer ATMfronttop;
    ModelRenderer ATMfrontbottom;
    ModelRenderer ATMFrontright;
    ModelRenderer ATMFrontleft;
    ModelRenderer button1;
    ModelRenderer button2;
    ModelRenderer button3;
    ModelRenderer button3;
    ModelRenderer button2;
    ModelRenderer button1;
  
  public ModelATM()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      ATMBase = new ModelRenderer(this, 0, 0);
      ATMBase.addBox(-5F, 0F, -5F, 12, 12, 10);
      ATMBase.setRotationPoint(0F, 0F, 2F);
      ATMBase.setTextureSize(128, 64);
      ATMBase.mirror = true;
      setRotation(ATMBase, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 24);
      Shape1.addBox(0F, -4.933333F, 0F, 12, 5, 2);
      Shape1.setRotationPoint(-5F, 0F, 5F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 28, 24);
      Shape2.addBox(0F, 0F, 0F, 10, 2, 5);
      Shape2.setRotationPoint(-4F, 0F, 1F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.5205006F, 0F, 0F);
      ATMfronttop = new ModelRenderer(this, 44, 16);
      ATMfronttop.addBox(0F, 0F, 0F, 12, 4, 1);
      ATMfronttop.setRotationPoint(-5F, 0F, -4F);
      ATMfronttop.setTextureSize(128, 64);
      ATMfronttop.mirror = true;
      setRotation(ATMfronttop, 0F, 0F, 0F);
      ATMfrontbottom = new ModelRenderer(this, 44, 16);
      ATMfrontbottom.addBox(0F, 0F, 0F, 12, 5, 1);
      ATMfrontbottom.setRotationPoint(-5F, 7F, -4F);
      ATMfrontbottom.setTextureSize(128, 64);
      ATMfrontbottom.mirror = true;
      setRotation(ATMfrontbottom, 0F, 0F, 0F);
      ATMFrontright = new ModelRenderer(this, 44, 0);
      ATMFrontright.addBox(0F, 0F, 0F, 3, 3, 1);
      ATMFrontright.setRotationPoint(4F, 4F, -4F);
      ATMFrontright.setTextureSize(128, 64);
      ATMFrontright.mirror = true;
      setRotation(ATMFrontright, 0F, 0F, 0F);
      ATMFrontleft = new ModelRenderer(this, 44, 0);
      ATMFrontleft.addBox(0F, 0F, 0F, 3, 3, 1);
      ATMFrontleft.setRotationPoint(-5F, 4F, -4F);
      ATMFrontleft.setTextureSize(128, 64);
      ATMFrontleft.mirror = true;
      setRotation(ATMFrontleft, 0F, 0F, 0F);
      button1 = new ModelRenderer(this, 12, 31);
      button1.addBox(0F, -2F, 0F, 1, 1, 1);
      button1.setRotationPoint(-1F, 1F, -2F);
      button1.setTextureSize(128, 64);
      button1.mirror = true;
      setRotation(button1, 0F, 0F, 0F);
      button2 = new ModelRenderer(this, 16, 31);
      button2.addBox(0F, -2F, 0F, 1, 1, 1);
      button2.setRotationPoint(1F, 1F, -2F);
      button2.setTextureSize(128, 64);
      button2.mirror = true;
      setRotation(button2, 0F, 0F, 0F);
      button3 = new ModelRenderer(this, 20, 31);
      button3.addBox(0F, -2F, 0F, 1, 1, 1);
      button3.setRotationPoint(3F, 1F, -2F);
      button3.setTextureSize(128, 64);
      button3.mirror = true;
      setRotation(button3, 0F, 0F, 0F);
      button3 = new ModelRenderer(this, 8, 31);
      button3.addBox(0F, -2F, 0F, 1, 1, 1);
      button3.setRotationPoint(3F, 1F, 0F);
      button3.setTextureSize(128, 64);
      button3.mirror = true;
      setRotation(button3, 0F, 0F, 0F);
      button2 = new ModelRenderer(this, 4, 31);
      button2.addBox(0F, -2F, 0F, 1, 1, 1);
      button2.setRotationPoint(1F, 1F, 0F);
      button2.setTextureSize(128, 64);
      button2.mirror = true;
      setRotation(button2, 0F, 0F, 0F);
      button1 = new ModelRenderer(this, 0, 31);
      button1.addBox(0F, -2F, 0F, 1, 1, 1);
      button1.setRotationPoint(-1F, 1F, 0F);
      button1.setTextureSize(128, 64);
      button1.mirror = true;
      setRotation(button1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ATMBase.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    ATMfronttop.render(f5);
    ATMfrontbottom.render(f5);
    ATMFrontright.render(f5);
    ATMFrontleft.render(f5);
    button1.render(f5);
    button2.render(f5);
    button3.render(f5);
    button3.render(f5);
    button2.render(f5);
    button1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
