// Date: 23/08/2012 03:09:30
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelTall Atm extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer TopFront;
    ModelRenderer TopLight;
    ModelRenderer Shape4;
    ModelRenderer Shape4;
    ModelRenderer Shape4;
    ModelRenderer Shape4;
    ModelRenderer Screen;
    ModelRenderer Shape2;
  
  public ModelTall Atm()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, -32F, -7F, 16, 32, 8);
      Shape1.setRotationPoint(-8F, 24F, 7.466667F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      TopFront = new ModelRenderer(this, 0, 44);
      TopFront.addBox(0F, -6F, -4F, 16, 11, 7);
      TopFront.setRotationPoint(-8F, 19F, -2F);
      TopFront.setTextureSize(128, 64);
      TopFront.mirror = true;
      setRotation(TopFront, 0F, 0F, 0F);
      TopLight = new ModelRenderer(this, 0, 40);
      TopLight.addBox(-1F, -1F, -2F, 8, 2, 2);
      TopLight.setRotationPoint(-3F, -5F, -2F);
      TopLight.setTextureSize(128, 64);
      TopLight.mirror = true;
      setRotation(TopLight, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 34, 40);
      Shape4.addBox(0F, 0F, 0F, 5, 1, 1);
      Shape4.setRotationPoint(-2F, 19F, -7F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 20, 40);
      Shape4.addBox(0F, 0F, -1F, 5, 1, 2);
      Shape4.setRotationPoint(-2F, 16F, -7F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 46, 45);
      Shape4.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape4.setRotationPoint(3F, 16F, -7F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 46, 40);
      Shape4.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape4.setRotationPoint(-3F, 16F, -7F);
      Shape4.setTextureSize(128, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Screen = new ModelRenderer(this, 48, 9);
      Screen.addBox(0F, -4F, 0F, 6, 4, 2);
      Screen.setRotationPoint(-3F, 13F, -1F);
      Screen.setTextureSize(128, 64);
      Screen.mirror = true;
      setRotation(Screen, -0.4507907F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 46, 53);
      Shape2.addBox(-3F, -1F, 0F, 14, 3, 6);
      Shape2.setRotationPoint(-4F, -7F, -5F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    TopFront.render(f5);
    TopLight.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Shape4.render(f5);
    Screen.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
